In [1]:
from pathlib import Path
import sys

print('Python 실행 파일:', sys.executable)
print('현재 작업 폴더:', Path.cwd())

Python 실행 파일: c:\dev\llm-data-analysis-course\.venv\Scripts\python.exe
현재 작업 폴더: c:\dev\llm-data-analysis-course\notebooks\ch04

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

PROJECT_ROOT = Path.cwd()
PROJECT_ROOT = PROJECT_ROOT.parent

if not (PROJECT_ROOT / 'data' / 'raw').exists() and (PROJECT_ROOT.parent / 'data' / 'raw').exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / 'data' / 'raw'
sns.set_theme(style='whitegrid')

print('프로젝트 루트:', PROJECT_ROOT)
print('데이터 폴더:', DATA_DIR)
print('데이터 폴더 존재 여부:', DATA_DIR.exists())

프로젝트 루트: c:\dev\llm-data-analysis-course
데이터 폴더: c:\dev\llm-data-analysis-course\data\raw
데이터 폴더 존재 여부: True

In [6]:
customers_path = DATA_DIR / 'customers.csv'

if not customers_path.exists():
    raise FileNotFoundError(
        f'{customers_path} 파일이 없습니다. '
        '프로젝트 루트에서 python scripts/generate_sample_data.py를 실행하세요.'
    )

df_customers = pd.read_csv(customers_path)
df_customers.head()

   customer_id name gender  age city signup_date
0            1  김수민      F   19   광주  2024-08-14
1            2  김정호      F   32   대구  2025-12-28
2            3  이경수      F   61   성남  2024-08-07
3            4  조영호      F   55   울산  2026-06-08
4            5  이예원      F   19   부산  2024-11-08

In [8]:
customers_over_30 = df_customers[df_customers["age"] >= 30]

print(customers_over_30)

     customer_id name gender  age city signup_date
1              2  김정호      F   32   대구  2025-12-28
2              3  이경수      F   61   성남  2024-08-07
3              4  조영호      F   55   울산  2026-06-08
5              6  김지원      F   32   성남  2026-08-22
6              7  이상현      F   53   인천  2025-02-06
..           ...  ...    ...  ...  ...         ...
141          142  하서연      F   32   서울  2023-10-04
142          143  김예은      F   43   대전  2024-02-27
144          145  조정호      M   59   성남  2024-02-27
145          146  김숙자      M   61   성남  2026-02-17
149          150  조미영      M   40   대전  2026-01-29

[111 rows x 6 columns]

In [ ]:
df_customers["city"].value_counts(dropna=False)

In [ ]:
df_customers.sort_values(
    "city",
    ascending=False
).head(10)

     customer_id name gender  age city signup_date
102          103  장미정      M   34   인천  2024-12-12
66            67  심서영      F   55   인천  2025-01-03
19            20  백영호      F   20   인천  2025-01-03
18            19  김성수      M   54   인천  2024-10-22
139          140  권광수      M   32   인천  2025-02-27
79            80  김현우      F   30   인천  2024-05-11
84            85  김선영      F   23   인천  2024-02-09
130          131  곽영자      F   40   인천  2025-12-29
20            21  박중수      M   23   인천  2026-05-28
64            65  손상호      F   33   인천  2026-03-14

In [19]:
customers_work = df_customers.copy ( )
customers_work[ "grade" ] =  'VIP'

print(customers_work.head(10))

   customer_id name gender  age city signup_date grade
0            1  김수민      F   19   광주  2024-08-14   VIP
1            2  김정호      F   32   대구  2025-12-28   VIP
2            3  이경수      F   61   성남  2024-08-07   VIP
3            4  조영호      F   55   울산  2026-06-08   VIP
4            5  이예원      F   19   부산  2024-11-08   VIP
5            6  김지원      F   32   성남  2026-08-22   VIP
6            7  이상현      F   53   인천  2025-02-06   VIP
7            8  이성호      M   32   수원  2025-02-18   VIP
8            9  송지민      M   69   서울  2025-12-14   VIP
9           10  유도현      F   62   울산  2024-12-01   VIP